[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "microphone=(self)"
    Content-Security-Policy = "default-src 'self'; media-src 'self'; connect-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://pubertytechnicallyknowhow.com; style-src 'self' 'unsafe-inline'"
